-- ============================================================
-- IMPORT PENGELUARAN DARI BUKU KAS - 2026-04 s.d. 2026-05
-- Dibuat otomatis oleh tools/siapkan-pengeluaran-buku-kas.py
-- Jalankan di D1 Console, database: your-home-checkin
--
-- 126 pengeluaran | Rp 80.862.098,08
-- 1 pemasukan (uang masuk) | Rp 2.000.000
-- Penanda data: created_by = 'import-pengeluaran-202604-202605'.
-- Aman dijalankan ulang: baris berpenanda ini dihapus dulu, lalu ditulis lagi.
-- Keterangan bertanda '(di luar operasional)' tidak dihitung sebagai beban properti.
-- ============================================================

DELETE FROM finance_entries WHERE created_by = 'import-pengeluaran-202604-202605';

INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0001', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-01', 300000, 'Sedot WC', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0002', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-01', 50000, 'Sambungan Pipa T', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0003', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-01', 50000, 'Tips Anter Lemari', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0004', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-01', 503000, 'Listrik', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0005', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-04-01', 100000, 'Keamanan', 'Rizwan Gustiawan', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0006', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-04-01', 150000, 'Sampah dan Kebersihan', 'Wiwin', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0007', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-01', 150000, 'Sampah', 'Siti Maelah', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0008', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-01', 70000, 'Iuran Warga', 'Pak Agus RT', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0009', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-01', 152500, 'Keamanan', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0010', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-04-01', 6801346, 'Sharing Owner · Desember, Januari (di luar operasional)', 'Rouven Sylviano', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0011', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-04-01', 7013305, 'Sharing Owner · November, Desember, Januari (di luar operasional)', 'Rouven Sylviano', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0012', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-04-03', 24000, 'Galon', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0013', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-04-04', 600000, 'Service Pompa dan Water Heater', 'Arief Artiyan', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0014', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-04-04', 126000, 'Beli Air · Pompa mati', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0015', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-04-04', 17500, 'Kabel USB', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0016', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-04-07', 2792207, 'Gaji · Maret', 'CSO Rezza', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0017', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-04-07', 969451, 'Gaji · Maret', 'CSO Yono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0018', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-04-07', 310958, 'Pendapatan Sewa · Jonathan Nathaniel · lt 18 (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0019', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-04-07', 1182175, 'Pendapatan Sewa · Felix ZhiQun · lt 11 (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0020', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-04-07', 455714, 'Pendapatan Sewa · Mia Chairunisa · lt 11 (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0021', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-04-07', 392986, 'Pendapatan Sewa · Karina Purwandari · lt 18 (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0022', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-04-07', 300000, 'Listrik · QRIS', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0023', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-07', 1003000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0024', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-04-08', 295000, 'Refund Konsumen Booking · Muhamad Sugara Teja · 7 Maret', '', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0025', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-08', 156000, 'Lampu', 'DANA', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0026', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-08', 70000, 'Duplikat Kunci Gembok (5pcs)', 'CSO Rezza', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0027', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-11', 366690, 'Internet', 'Megavision', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0028', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-04-11', 749608, 'IPL · April', 'P3SRS', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0029', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-04-11', 412600, 'IPL · April', 'KBP Padalarang', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0030', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-04-11', 440658, 'IPL · April', 'Ikatan Warga Villa Istana Bunga', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0031', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-04-11', 200000, 'Sealent Toilet', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0032', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-04-11', 321900, 'Internet', 'Indonet', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0033', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-11', 310000, 'Tabung Gas & Isi 12kg', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('inc-202604-0001', 'income', 'income-other', 'Pemasukan Lain', NULL, '', '2026-04-11', 2000000, 'Kompensasi Maling · Andre CSO (uang masuk)', 'Pak Hadi', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0034', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-04-11', 164200, 'Standing Banner Don''t Disturb', 'Shopee', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0035', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-04-13', 424800, 'Internet', 'Indihome', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0036', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-04-13', 391911, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0037', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-04-13', 621672, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0038', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-04-16', 125000, 'Banner Davion', 'Asep Sapta', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0039', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-17', 265900, 'Konsumsi Penghuni · Kemalingan Gas · Indomaret', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0040', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-17', 500000, 'Reserse Polsek Sukajadi', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0041', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-04-17', 503000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0042', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-04-17', 100000, 'Hampers KBP · Komplain Bau Toilet · Otak-otak', 'Hendra', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0043', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-04-17', 14000, 'Biaya ADM', 'BCA', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0044', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-19', 1003000, 'Listrik', '', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0045', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('HIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('HIB')), ''), '2026-04-20', 150000, 'Aplikasi Invoice', 'Asep Sapta', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0046', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-04-20', 1000250, 'Pendapatan Sewa · Deny Rian - 14 Maret · lt 18 (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0047', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-21', 30000, 'Duplikat Kunci Gembok', 'CSO Yono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0048', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-04-21', 2000000, 'Perbaikan Pompa · DP', 'Arief Artiyan', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0049', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-04-22', 500000, 'Perbaikan Pompa · Pelunasan', 'Arief Artiyan', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0050', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-22', 3500000, 'Perbaikan Bocor', 'Muhammad Zian Ramdani', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0051', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-04-24', 45000, 'Gas Melon, Galon (2pcs)', 'CSO Rezza', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0052', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-04-26', 58500, 'Galon · 3 pcs', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0053', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-27', 3488500, 'Perbaikan Bocor', 'Muhammad Zian Ramdani', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0054', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-04-30', 1851470, 'Kursi Fasum, Meja Belajar (3pcs), Asbak', 'Shopee', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202604-0055', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-04-30', 30.02, 'Pajak Bunga', 'BCA', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0001', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-02', 1003000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0002', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-02', 152500, 'Keamanan', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0003', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-05-02', 100000, 'Keamanan', 'Rizwan Gustiawan', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0004', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-05-02', 150000, 'Sampah dan Kebersihan', 'Wiwin', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0005', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-02', 150000, 'Sampah', 'Siti Maelah', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0006', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-02', 70000, 'Iuran Warga', 'Pak Agus RT', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0007', 'expense', 'expense-pest-control', 'Pest Control', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-02', 300000, 'Pest Control', 'Diki Permana', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0008', 'expense', 'expense-pest-control', 'Pest Control', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-05-02', 300000, 'Pest Control', 'Diki Permana', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0009', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-05-04', 502500, 'Kembali Deposit · Kamar 5 · Bimo Mandiri (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0010', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-05-06', 157500, 'Amenities · QRIS', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0011', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-06', 230000, 'Beli Air', 'Heri Pujiono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0012', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-07', 22750, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0013', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-05-07', 1091010, 'Gaji · April', 'CSO Yono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0014', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-05-07', 2320303, 'Gaji · April', 'CSO Rezza', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0015', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-08', 750000, 'Lemari Baju 1 pcs', 'Hade', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0016', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-08', 1800000, 'Perbaikan Pompa', 'Arief Artiyan', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0017', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-08', 230000, 'Beli Air', 'Heri Pujiono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0018', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-09', 230000, 'Beli Air', 'Heri Pujiono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0019', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-10', 200000, 'Perbaikan Pompa', 'Arief Artiyan', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0020', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-10', 230000, 'Beli Air', 'Heri Pujiono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0021', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-10', 230000, 'Beli Air', 'Heri Pujiono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0022', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-11', 366690, 'Internet', 'Megavision', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0023', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-05-11', 476658, 'IPL · Mei', 'Ikatan Warga Villa Istana Bunga', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0024', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-05-11', 903400, 'IPL', 'P3SRS', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0025', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-05-11', 467000, 'IPL', 'KBP Padalarang', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0026', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-11', 209000, 'Isi Ulang Gas', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0027', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-11', 153099, 'Kipas Angin · Shopee', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0028', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-05-11', 75000, 'Galon 3 pcs', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0029', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-11', 230000, 'Beli Air', 'Heri Pujiono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0030', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-11', 230000, 'Beli Air', 'Heri Pujiono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0031', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-12', 460000, 'Beli Air', 'Heri Pujiono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0032', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-13', 900000, 'Tuker Tambah Pompa', 'Amir Sutrisna', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0033', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-13', 1050000, 'Perbaikan Pompa', 'Amir Sutrisna', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0034', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-05-14', 424800, 'Internet', 'Indihome', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0035', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-05-14', 1029642, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0036', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-05-14', 618843, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0037', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-14', 350000, 'Cor dan ganti radar', 'Amir Sutrisna', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0038', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('HIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('HIB')), ''), '2026-05-15', 1156620, 'Perpanjang Hosting & Domain', 'Exabytes', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0039', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-15', 30000, 'Kartu RFID Bardi', 'Shopee', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0040', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-05-15', 102000, 'Gantungan Baju · Shopee', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0041', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-15', 1003000, 'Listrik', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0042', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-15', 66000, 'Tips Kirim Lemari, Duplikat Kunci Gerbang', '', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0043', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('HIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('HIB')), ''), '2026-05-15', 14000, 'Biaya ADM', 'BCA', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0044', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-05-16', 135000, 'Abodemen Parkir', 'P3SRS', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0045', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-16', 31000, 'Baterai Bardi · Gojek', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0046', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-05-18', 3000000, 'Renovasi Dago', 'Yuli Wulandari', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0047', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-05-18', 321900, 'Internet', 'Indonet', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0048', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-18', 109800, 'Cover Duplikat Kartu Bardi', 'Shopee', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0049', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-05-20', 7000000, 'Renovasi Dago', 'Yuli Wulandari', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0050', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-05-20', 22000, 'Tissue', 'CSO Rezza', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0051', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-20', 136000, 'Peralatan Kebersihan', 'CSO Yono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0052', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-05-20', 25000, 'Peralatan Kebersihan', 'CSO Yono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0053', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-05-20', 30000, 'Peralatan Dapur', '', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0054', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-23', 230000, 'Beli Air', 'Heri Pujiono', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0055', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-23', 180000, 'Beli Air · BRI', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0056', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-05-24', 300000, 'Listrik', 'CSO Rezza', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0057', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-24', 100000, 'Check Pompa', 'Amir Sutrisna', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0058', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-05-25', 503000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0059', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-05-26', 385000, 'Laundry · Maret', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0060', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-05-26', 150000, 'Laundry · Maret', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0061', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-05-26', 400000, 'Laundry · Maret', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0062', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-05-26', 50000, 'Laundry · Maret', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0063', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-05-26', 500000, 'Laundry · April', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0064', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-05-26', 100000, 'Laundry · April', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0065', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-05-26', 385000, 'Laundry · April', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0066', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-05-26', 200000, 'Laundry · April', 'Andri Fernando', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0067', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-29', 1003000, 'Listrik', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0068', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-05-29', 40000, 'Duplikat Kunci Gembok', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0069', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-05-31', 51200, 'Baygon dan Galon', 'CSO Rezza', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0070', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-05-31', 1365000, 'Perbaikan Dago', 'Yuli Wulandari', 'once', 'import-pengeluaran-202604-202605', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202605-0071', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('HIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('HIB')), ''), '2026-05-31', 52.06, 'Pajak Bunga', 'BCA', 'once', 'import-pengeluaran-202604-202605', datetime('now'));

-- PEMERIKSAAN - jalankan terpisah (D1 hanya menampilkan hasil query pertama)
SELECT COUNT(*) AS jumlah, COALESCE(SUM(amount), 0) AS nilai FROM finance_entries WHERE created_by = 'import-pengeluaran-202604-202605';

SELECT entry_date, description, amount FROM finance_entries WHERE created_by = 'import-pengeluaran-202604-202605' ORDER BY entry_date;
