-- ============================================================
-- IMPORT PENGELUARAN DARI BUKU KAS - 2026-02 s.d. 2026-03
-- Dibuat otomatis oleh tools/siapkan-pengeluaran-buku-kas.py
-- Jalankan di D1 Console, database: your-home-checkin
--
-- 99 pengeluaran | Rp 87.169.625,44
-- Penanda data: created_by = 'import-pengeluaran-202602-202603'.
-- Aman dijalankan ulang: baris berpenanda ini dihapus dulu, lalu ditulis lagi.
-- Keterangan bertanda '(di luar operasional)' tidak dihitung sebagai beban properti.
-- ============================================================

DELETE FROM finance_entries WHERE created_by = 'import-pengeluaran-202602-202603';

INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0001', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-02-01', 300000, 'Listrik · Qris', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0002', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-01', 51210, 'Gembok', '', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0003', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-01', 176000, 'Ganti Kunci Kamar', 'Gopay', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0004', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-01', 52500, 'Duplikat Kunci Gembok', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0005', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-01', 209000, 'Isi Ulang Tabung Gas · Qris', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0006', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-02-02', 1757407, 'Gaji', 'CSO Yono', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0007', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-02-02', 2503704, 'Gaji', 'CSO Rezza', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0008', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-02-02', 100000, 'Keamanan', 'Rizwan Gustiawan', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0009', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-02-02', 150000, 'Kebersihan', 'Wiwin', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0010', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-02', 150000, 'Sampah', 'Siti Maelah', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0011', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-02', 72500, 'Iuran Warga', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0012', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-02', 152500, 'Keamanan', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0013', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-02', 202500, 'Pembersihan Pohon Depan Orange', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0014', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-04', 762755, 'Round Up, Penyemprot, Tong Sampah, Kursi', 'Shopee', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0015', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-02-04', 600000, 'Laundry · Desember, Januari', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0016', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-02-04', 200000, 'Laundry · Desember, Januari', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0017', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-02-04', 805000, 'Laundry · Desember, Januari', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0018', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-02-04', 450000, 'Laundry · Desember, Januari', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0019', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-05', 100000, 'Cek CCTV', 'Lidya', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0020', 'expense', 'expense-pest-control', 'Pest Control', NULL, '', '2026-02-05', 950000, 'Pest Control', 'Diki Permana', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0021', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-02-07', 51800, 'Baygon · Komplain Lalat', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0022', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-09', 366690, 'Internet', 'Megavision', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0023', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-02-09', 440658, 'IPL · Febuari', 'Ikatan Warga Villa Istana Bunga', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0024', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-02-09', 127990, 'IPL · Febuari', 'P3SRS', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0025', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-02-13', 366689, 'Listrik · Febuari', 'PLN Jabar', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0026', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-02-13', 578652, 'Listrik · Febuari', 'PLN Jabar', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0027', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-02-13', 946900, 'IPL · Febuari', 'KBP Padalarang', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0028', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-02-13', 424800, 'Internet · Febuari', 'Indihome', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0029', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-14', 1003000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0030', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-02-14', 596425, 'Pendapatan Sewa · dari Tiketcom · Syifa (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0031', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-02-14', 8250600, 'Pendapatan Sewa · dari Tiketcom · Adella (25 Sept) (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0032', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-14', 170000, 'Perbaikan Shower & Las Branghang', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0033', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-02-16', 321900, 'Internet · Febuari', 'Indonet', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0034', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-02-17', 4716720, 'Bagi Hasil HIB · September (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0035', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-02-17', 8719318, 'Bagi Hasil HIB · Oktober (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0036', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-02-17', 7893020, 'Bagi Hasil HIB · November (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0037', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-02-17', 10372211, 'Bagi Hasil HIB · Desember (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0038', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('HIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('HIB')), ''), '2026-02-20', 14000, 'Biaya ADM', 'BCA', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0039', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('SUD-18')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('SUD-18')), ''), '2026-02-22', 320484, 'Refund Konsumen Agoda · 2026-02-21 · DB', 'Dany Kurniawan', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0040', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-02-24', 43700, 'Aqua · Desember', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0041', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-02-24', 20000, 'Aqua · Desember', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0042', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-02-24', 52000, 'Baterai AAA · Desember', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0043', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-02-24', 37000, 'Aqua dan Es Batu · Desember', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0044', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-02-24', 26500, 'Kunci Pas GT · Januari', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0045', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-24', 100000, 'Pelampung Closet · Januari', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0046', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-02-24', 108000, 'Baterai dan Gas · Januari', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0047', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-02-24', 162500, 'Alat Isi Ulang Tabung Gas Portable & Gas Melon · Febuari', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0048', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-02-24', 106000, 'Otomatis Sanyo, Aqua 3pcs · Febuari', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0049', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-02-25', 60000, 'Galon & Gas', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0050', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-25', 90000, 'Las Besi Solokan', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0051', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-02-25', 120000, 'Pasang Exhaust', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0052', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-02-25', 180000, 'Perbaikan Dago · Desember', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0053', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-25', 50000, 'Pasang Banner', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0054', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-25', 200000, 'Helper Pindahan Orange · 4 orang', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0055', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('HIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('HIB')), ''), '2026-02-25', 100000, 'Pulsa HIB · Januari', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0056', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-02-25', 11161948, 'Bagi Hasil HIB · Januari (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0057', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-27', 607691, 'Pemasangan Listrik Baru Kamar No 2', 'PLN Jabar', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0058', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-02-27', 1003000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202602-0059', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('HIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('HIB')), ''), '2026-02-28', 53.44, 'Pajak Bunga', 'BCA', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0001', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-03-01', 300000, 'THR dan Iuran Keamanan', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0002', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-03-01', 300000, 'THR dan Iuran Sampah', 'Siti Maelah', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0003', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-03-01', 140000, 'THR dan Iuran Warga', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0004', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-03-01', 100000, 'Keamanan', 'Rizwan Gustiawan', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0005', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-03-01', 150000, 'Sampah dan Kebersihan', 'Wiwin', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0006', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-03-05', 1065278, 'Gaji · Febuari', 'CSO Yono', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0007', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-03-05', 2076389, 'Gaji · Febuari', 'CSO Rezza', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0008', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-03-07', 250000, 'Laundry · Febuari', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0009', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-03-07', 150000, 'Laundry · Febuari', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0010', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-03-07', 140000, 'Laundry · Febuari', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0011', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-03-11', 366690, 'Internet', 'Megavision', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0012', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-03-11', 424800, 'Internet', 'Indihome', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0013', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-03-11', 448658, 'IPL · Maret', 'Ikatan Warga Villa Istana Bunga', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0014', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-03-11', 801880, 'IPL · Maret', 'P3SRS', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0015', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-03-11', 400400, 'IPL', 'KBP Padalarang', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0016', 'expense', 'expense-pest-control', 'Pest Control', NULL, '', '2026-03-11', 600000, 'Pest Control', 'Diki Permana', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0017', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-03-11', 366689, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0018', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-03-11', 494072, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0019', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-03-16', 1003000, 'Listrik', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0020', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-03-18', 214000, 'Gunting Stek dan Amenities', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0021', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-03-18', 321900, 'Internet', 'Indonet', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0022', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-03-18', 85000, 'Amenities', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0023', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-03-19', 203000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0024', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('HIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('HIB')), ''), '2026-03-20', 14000, 'Biaya ADM', 'BCA', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0025', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-03-23', 45000, 'Kabel LAN', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0026', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-03-23', 33500, 'Galon & Gas', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0027', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-03-23', 867000, 'THR CSO', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0028', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-03-24', 291444, 'Mi Stick Netflix', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0029', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-03-24', 310000, 'Tabung dan Isi Gas 12 kg', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0030', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-03-24', 210300, 'Amenities', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0031', 'expense', 'expense-salary', 'Gaji', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-03-24', 150000, 'CSO Harian', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0032', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-03-24', 115000, 'Tabung Gas 12 kg', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0033', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-03-26', 81250, 'Trashbag, Tissue, So Klin', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0034', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-03-26', 36250, 'Galon & Gas', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0035', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-03-27', 26000, 'Internet', 'Orbit', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0036', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-03-27', 1478800, 'Lampu · Azko', 'Andri Fernando', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0037', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-03-27', 100000, 'Fitting Lampu', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0038', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-03-28', 203000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0039', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-03-30', 1001000, 'Meja Belajar 3 pcs', 'Shopee', 'once', 'import-pengeluaran-202602-202603', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202603-0040', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-03-31', 2150000, 'Lemari Baju 3 pcs', 'Hade', 'once', 'import-pengeluaran-202602-202603', datetime('now'));

-- PEMERIKSAAN - jalankan terpisah (D1 hanya menampilkan hasil query pertama)
SELECT COUNT(*) AS jumlah, COALESCE(SUM(amount), 0) AS nilai FROM finance_entries WHERE created_by = 'import-pengeluaran-202602-202603';

SELECT entry_date, description, amount FROM finance_entries WHERE created_by = 'import-pengeluaran-202602-202603' ORDER BY entry_date;
