-- ============================================================
-- IMPORT PENGELUARAN DARI BUKU KAS - 2026-08 s.d. 2026-08
-- Dibuat otomatis oleh tools/siapkan-pengeluaran-buku-kas.py
-- Jalankan di D1 Console, database: your-home-checkin
--
-- 67 pengeluaran | Rp 44.003.992,84
-- Penanda data: created_by = 'import-pengeluaran-202608'.
-- Aman dijalankan ulang: baris berpenanda ini dihapus dulu, lalu ditulis lagi.
-- Keterangan bertanda '(di luar operasional)' tidak dihitung sebagai beban properti.
-- ============================================================

DELETE FROM finance_entries WHERE created_by = 'import-pengeluaran-202608';

INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0001', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-08-01', 152500, 'Keamanan', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0002', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-01', 100000, 'Keamanan', 'Rizwan Gustiawan', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0003', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-01', 150000, 'Sampah dan Kebersihan', 'Wiwin', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0004', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-08-01', 150000, 'Sampah', 'Siti Maelah', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0005', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-08-01', 70000, 'Iuran Warga', 'Pak Agus RT', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0006', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-08-01', 100000, 'Abodemen Parkir', 'P3SRS', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0007', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-08-01', 100600, 'PDAM', 'Tirtawening', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0008', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-02', 110000, 'Internet', 'Orbit', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0009', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-02', 44800, 'Batre Mic', 'CSO Rezza', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0010', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-08-02', 270000, 'Laundry · Mei', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0011', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-02', 750000, 'Laundry · Mei', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0012', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-08-02', 350000, 'Laundry · Mei', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0013', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-08-02', 330000, 'Laundry · Juni', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0014', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-02', 850000, 'Laundry · Juni', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0015', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-02', 200000, 'Laundry · Juni', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0016', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-08-02', 200000, 'Laundry · Juni', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0017', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-08-02', 450000, 'Laundry · Juli', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0018', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-02', 600000, 'Laundry · Juli', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0019', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-02', 450000, 'Laundry · Juli', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0020', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-08-02', 300000, 'Laundry · Juli', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0021', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-08-03', 502500, 'Kelebihan Transfer · Kamar 14 · Andri Fernando', 'Aris Siswanto', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0022', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-08-03', 30000, 'Sumbangan 17 Agt · CSO Rezza', 'Pak Agus RT', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0023', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-08-04', 14000, 'Biaya ADM', 'BCA', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0024', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-08-05', 700000, 'Tuker Tambah Pompa Kebakaran', 'Amir Sutrisna', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0025', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-08-05', 858221, 'Gaji', 'CSO Yono', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0026', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-08-05', 2037813, 'Gaji', 'CSO Rezza', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0027', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-08-05', 254755, 'Gaji', 'CSO Qeyla', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0028', 'expense', 'expense-salary', 'Gaji', NULL, '', '2026-08-05', 187500, 'Gaji', 'CSO Denny', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0029', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-06', 75000, '3 Galon', 'CSO Rezza', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0030', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-08-06', 8462509, 'Bagi Hasil Owner · Juni Juli (di luar operasional)', 'Rouven Sylviano', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0031', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-08-06', 4835441, 'Bagi Hasil Owner · Juni Juli (di luar operasional)', 'Rouven Sylviano', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0032', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-08-06', 1596716, 'Bagi Hasil HIB · Febuari (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0033', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-08-06', 8256160, 'Bagi Hasil HIB · Maret (di luar operasional)', 'Andri Fernando', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0034', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-08-06', 400000, 'Perbaikan Listrik Konslet', 'Muhammad Zian Ramdani', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0035', 'expense', 'expense-pest-control', 'Pest Control', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-07', 600000, 'Pest Control', 'Diki Permana', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0036', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-08-08', 1003000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0037', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-09', 99000, 'Pasang Indihome', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0038', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-08-09', 40000, 'Aqua 2 Galon', 'CSO Rezza', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0039', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-08-09', 239000, 'Gas 12 kg', 'CSO Rezza', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0040', 'expense', 'expense-dues', 'Iuran', NULL, '', '2026-08-09', 100000, 'Sumbangan 17 Agt · CSO Rezza', 'Pak Agus RT', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0041', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-08-10', 300000, 'Listrik', 'CSO Rezza', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0042', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-12', 503000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0043', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-13', 28000, 'Gas Melon', 'CSO Rezza', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0044', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-08-13', 366690, 'Internet', 'Megavision', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0045', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-13', 424800, 'Internet', 'Indihome', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0046', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-13', 569658, 'IPL', 'Ikatan Warga Villa Istana Bunga', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0047', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-08-13', 919816, 'IPL', 'P3SRS', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0048', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-08-13', 418700, 'IPL', 'KBP Padalarang', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0049', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-08-13', 436948, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0050', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-13', 906921, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0051', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-16', 150000, 'Ganti Pelampung', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0052', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-08-16', 25300, 'Aqua Galon', 'CSO Qeyla', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0053', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-08-16', 44500, 'Batre Bardi', 'CSO Qeyla', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0054', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-08-20', 43000, 'Aqua 2 Galon', 'CSO Qeyla', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0055', 'expense', 'expense-amenities', 'Amenities', NULL, '', '2026-08-20', 128000, 'Gas Portable, Aqua 1 Galon', 'CSO Qeyla', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0056', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-20', 90000, 'Gojek', 'CSO Hendrik', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0057', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-20', 90000, 'Gojek', 'CSO Hendrik', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0058', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-08-20', 321900, 'Internet', 'Indonet', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0059', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-08-22', 1003000, 'Listrik', 'PLN Jabar', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0060', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-22', 110000, 'Indihome Problem · Hardiman', 'Orbit', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0061', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-08-22', 47200, 'Aqua 2 Galon', 'CSO Qeyla', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0062', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-24', 46000, 'Aqua 2 Galon', 'Hardiman Liugiarto', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0063', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-08-24', 21500, 'Aqua Galon', 'CSO Qeyla', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0064', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-24', 500000, 'Ruqiah', 'Muhammad Zian Ramdani', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0065', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-08-28', 445000, 'Service Thermostart', 'Arief Artiyan', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0066', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-08-28', 44500, 'Batre Remot TV', 'CSO Rezza', 'once', 'import-pengeluaran-202608', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202608-0067', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-08-31', 44.84, 'Pajak Bunga', 'BCA', 'once', 'import-pengeluaran-202608', datetime('now'));

-- PEMERIKSAAN - jalankan terpisah (D1 hanya menampilkan hasil query pertama)
SELECT COUNT(*) AS jumlah, COALESCE(SUM(amount), 0) AS nilai FROM finance_entries WHERE created_by = 'import-pengeluaran-202608';

SELECT entry_date, description, amount FROM finance_entries WHERE created_by = 'import-pengeluaran-202608' ORDER BY entry_date;
