-- ============================================================
-- IMPORT PENGELUARAN DARI BUKU KAS - 2026-01 s.d. 2026-01
-- Dibuat otomatis oleh tools/siapkan-pengeluaran-buku-kas.py
-- Jalankan di D1 Console, database: your-home-checkin
--
-- 39 pengeluaran | Rp 15.132.935
-- Penanda data: created_by = 'import-pengeluaran-202601'.
-- Aman dijalankan ulang: baris berpenanda ini dihapus dulu, lalu ditulis lagi.
-- Keterangan bertanda '(di luar operasional)' tidak dihitung sebagai beban properti.
-- ============================================================

DELETE FROM finance_entries WHERE created_by = 'import-pengeluaran-202601';

INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0001', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-01-02', 100000, 'Keamanan', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0002', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-02', 150000, 'Kebersihan Sampah', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0003', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-02', 150000, 'Iuran Sampah', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0004', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-02', 225000, 'Keamanan', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0005', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-01-04', 52500, 'Galon', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0006', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-01-04', 53700, 'Sabun, Tissue, Sampo', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0007', 'expense', 'expense-dues', 'Iuran', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-01-06', 1613568, 'IPL', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0008', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-08', 366690, 'Internet', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0009', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-01-08', 613619, 'Prabayar', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0010', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-01-08', 424800, 'Internet', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0011', 'expense', 'expense-pest-control', 'Pest Control', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-01-08', 300000, 'Pest Kontrol', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0012', 'expense', 'expense-pest-control', 'Pest Control', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-01-08', 300000, 'Pest Kontrol', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0013', 'expense', 'expense-pest-control', 'Pest Control', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-01-08', 350000, 'Pest Kontrol', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0014', 'expense', 'expense-pest-control', 'Pest Control', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-08', 300000, 'Pest Kontrol', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0015', 'expense', 'expense-repair', 'Perbaikan', NULL, '', '2026-01-09', 285000, 'Alat Kebersihan', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0016', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-10', 237734, 'Peralatan Makan', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0017', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-01-10', 51000, 'Galon', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0018', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-01-15', 575000, 'Exhaust dan lampu', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0019', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-01-15', 300000, 'Bensin', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0020', 'expense', 'expense-internet', 'WiFi / Internet', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-01-16', 176526, 'Internet', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0021', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-17', 1003000, 'Token', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0022', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-01-18', 500000, 'Ganti Sensor Termohit - Water Heater ga panas', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0023', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-18', 589762, 'Meja Belajar dan Lemari Baju', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0024', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GH-KBP')), ''), '2026-01-18', 366689, 'Prabayar', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0025', 'expense', 'expense-other', 'Lain-lain', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-19', 850000, 'Sewa Truck Pindahan', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0026', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-01-19', 93300, 'Jas Ujan CSO - Tokped Rezza', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0027', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-19', 55500, 'Laundry konsumen harian', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0028', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VIB')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VIB')), ''), '2026-01-19', 102800, 'Batre Mic', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0029', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-19', 80000, 'Lampu Dapur', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0030', 'expense', 'expense-amenities', 'Amenities', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('GCB-03')), ''), '2026-01-19', 22000, 'Galon', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0031', 'expense', 'expense-laundry', 'Laundry', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-19', 40000, 'Laundry selimut konsumen harian', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0032', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-20', 44200, 'Listrik Kamar Kos', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0033', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-21', 177000, 'Kunci, Palu, Obeng, Tang - Peralatan Kosan', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0034', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-01-21', 400000, 'Service Freezer', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0035', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-22', 540000, 'Bantal 12pcs, konsumen harian', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0036', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('VBD')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('VBD')), ''), '2026-01-22', 75000, 'Adaptor Charger Speaker Karaoke', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0037', 'expense', 'expense-repair', 'Perbaikan', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-22', 668200, 'Meja Belajar', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0038', 'expense', 'expense-other', 'Lain-lain', NULL, '', '2026-01-24', 1897347, 'Refund Tamu Dago, DB - DB Vitri Nur Vadilah - 24 Jan', '', 'once', 'import-pengeluaran-202601', datetime('now'));
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at) VALUES ('exp-202601-0039', 'expense', 'expense-electricity', 'Listrik', (SELECT COALESCE(NULLIF(TRIM(dashboard_id), ''), id) FROM properties WHERE UPPER(property_code) = UPPER('KDO')), COALESCE((SELECT name FROM properties WHERE UPPER(property_code) = UPPER('KDO')), ''), '2026-01-28', 1003000, 'Token', '', 'once', 'import-pengeluaran-202601', datetime('now'));

-- PEMERIKSAAN - jalankan terpisah (D1 hanya menampilkan hasil query pertama)
SELECT COUNT(*) AS jumlah, COALESCE(SUM(amount), 0) AS nilai FROM finance_entries WHERE created_by = 'import-pengeluaran-202601';

SELECT entry_date, description, amount FROM finance_entries WHERE created_by = 'import-pengeluaran-202601' ORDER BY entry_date;
