INSERT OR IGNORE INTO dashboard_bookings (id, property_id, property_name, property_code, guest, platform, status, checkin, checkout, nights, amount, extra_bed_quantity, extra_bed_price, cleaning_fee, platform_fee_pct, note, cancellation_reason, refund_amount, income_entry_id, created_by, created_at, updated_at) VALUES ('BKE20270121-0001', 'Dago', '', 'Dago', 'Nur Haziqah Binti Yahya', 'Booking.com', 'Confirmed', '2027-01-21', '2027-01-23', 2, 2016000, 0, 0, 0, 0, 'Import Excel 2027', '', 0, 'booking-income-BKE20270121-0001', 'import-excel-2027', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_bookings (id, property_id, property_name, property_code, guest, platform, status, checkin, checkout, nights, amount, extra_bed_quantity, extra_bed_price, cleaning_fee, platform_fee_pct, note, cancellation_reason, refund_amount, income_entry_id, created_by, created_at, updated_at) VALUES ('BKE20270123-0002', 'SUD-19', '', 'SUD-19', 'Salma Zahira Fathina', 'Airbnb', 'Confirmed', '2027-01-23', '2027-01-24', 1, 794335, 0, 0, 0, 0, 'Import Excel 2027', '', 0, 'booking-income-BKE20270123-0002', 'import-excel-2027', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_bookings (id, property_id, property_name, property_code, guest, platform, status, checkin, checkout, nights, amount, extra_bed_quantity, extra_bed_price, cleaning_fee, platform_fee_pct, note, cancellation_reason, refund_amount, income_entry_id, created_by, created_at, updated_at) VALUES ('BKE20270410-0003', 'Dago', '', 'Dago', 'Abdul Mudjib', 'Booking.com', 'Confirmed', '2027-04-10', '2027-04-12', 2, 2240000, 0, 0, 0, 0, 'Import Excel 2027', '', 0, 'booking-income-BKE20270410-0003', 'import-excel-2027', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_bookings (id, property_id, property_name, property_code, guest, platform, status, checkin, checkout, nights, amount, extra_bed_quantity, extra_bed_price, cleaning_fee, platform_fee_pct, note, cancellation_reason, refund_amount, income_entry_id, created_by, created_at, updated_at) VALUES ('BKE20270416-0004', 'SUD-19', '', 'SUD-19', 'Kai Dunlap', 'Airbnb', 'Confirmed', '2027-04-16', '2027-05-07', 21, 13267739, 0, 0, 0, 0, 'Import Excel 2027', '', 0, 'booking-income-BKE20270416-0004', 'import-excel-2027', datetime('now'), datetime('now'));
INSERT OR IGNORE INTO dashboard_bookings (id, property_id, property_name, property_code, guest, platform, status, checkin, checkout, nights, amount, extra_bed_quantity, extra_bed_price, cleaning_fee, platform_fee_pct, note, cancellation_reason, refund_amount, income_entry_id, created_by, created_at, updated_at) VALUES ('BKE20270701-0005', 'Dago', '', 'Dago', 'Khalid Al Sayyari', 'Booking.com', 'Confirmed', '2027-07-01', '2027-07-28', 27, 24920000, 0, 0, 0, 0, 'Import Excel 2027', '', 0, 'booking-income-BKE20270701-0005', 'import-excel-2027', datetime('now'), datetime('now'));
UPDATE dashboard_bookings SET property_id = COALESCE(NULLIF(TRIM((SELECT dashboard_id FROM properties WHERE property_code = dashboard_bookings.property_code)), ''), (SELECT id FROM properties WHERE property_code = dashboard_bookings.property_code), 'BELUM-' || property_code), property_name = COALESCE((SELECT name FROM properties WHERE property_code = dashboard_bookings.property_code), 'Properti ' || property_code || ' - kode perlu diperiksa'), note = CASE WHEN (SELECT COUNT(*) FROM properties WHERE property_code = dashboard_bookings.property_code) = 0 AND note NOT LIKE '%KODE PERLU DIPERIKSA%' THEN note || ' - KODE PERLU DIPERIKSA' ELSE note END WHERE created_by = 'import-excel-2027';
INSERT OR IGNORE INTO finance_entries (id, kind, category_id, category_name, property_id, property_name, entry_date, amount, description, payee, recurrence, created_by, created_at)
SELECT b.income_entry_id, 'income', 'income-booking', 'Booking', b.property_id, b.property_name, b.checkin, b.amount, 'Booking ' || b.id || ' - ' || b.guest, b.platform, 'once', b.created_by, b.created_at
FROM dashboard_bookings b WHERE b.created_by = 'import-excel-2027';
SELECT COUNT(*) AS jumlah_booking, COALESCE(SUM(amount), 0) AS nilai_booking FROM dashboard_bookings WHERE created_by = 'import-excel-2027';
SELECT COUNT(*) AS jumlah_pemasukan, COALESCE(SUM(amount), 0) AS nilai_pemasukan FROM finance_entries WHERE created_by = 'import-excel-2027';
SELECT substr(checkin, 1, 7) AS bulan, COUNT(*) AS jumlah, COALESCE(SUM(amount), 0) AS nilai FROM dashboard_bookings WHERE created_by = 'import-excel-2027' GROUP BY bulan ORDER BY bulan;
SELECT property_code AS kode_perlu_diperiksa, COUNT(*) AS jumlah, COALESCE(SUM(amount), 0) AS nilai FROM dashboard_bookings WHERE created_by = 'import-excel-2027' AND property_id LIKE 'BELUM-%' GROUP BY property_code;
SELECT 'Dago' AS kode, (SELECT COUNT(*) FROM properties p WHERE p.property_code = 'Dago') AS ada_properti;
SELECT 'SUD-19' AS kode, (SELECT COUNT(*) FROM properties p WHERE p.property_code = 'SUD-19') AS ada_properti;
